// Protocol generation, routed through the persisting job pipeline (variant A):
// the protocol is generated by the worker via POST /meetings/:id/reprocess
// {kind:"protocol"} and persisted to the DB + protocol.md, instead of the old
// non-persisting POST /api/v1/protocols (which only returned markdown to an
// in-memory client cache that vanished on restart). When the meeting has no
// transcript yet we first transcribe via the SYNC POST /api/v1/transcribe
// (persists), then enqueue the protocol job and poll it to completion.
import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
import MeetingAssistant

Page {
    id: scr
    property var shell
    property var store
    property string meetingId
    property string meetingName
    property string audioPath
    property bool hasTranscript: false
    property bool autoStart: false

    // "idle"|"transcribing"|"transcriptFailed"|"generating"|"done"|"failed"
    property string st: "idle"
    property string errorMsg: ""
    // Id of the enqueued protocol job, polled to completion before navigating.
    property string jobId: ""

    // Per-generation template override, seeded from the server default
    // (decision #13). Editing it does NOT change the global default.
    property string templateName: ""
    Connections {
        target: SettingsStore
        function onLoadedChanged() {
            if (SettingsStore.loaded && scr.templateName.length === 0)
                scr.templateName = SettingsStore.defaultTemplate()
        }
    }

    function stateLabel() {
        switch (st) {
        case "idle": return qsTr("Готово к запуску")
        case "transcribing": return qsTr("Распознавание речи")
        case "generating": return qsTr("Составление протокола")
        case "done": return qsTr("Готово")
        case "transcriptFailed":
        case "failed": return qsTr("Ошибка")
        }
        return qsTr("Генерация")
    }

    function generate() {
        if (st !== "idle" && st !== "transcriptFailed" && st !== "failed")
            return
        errorMsg = ""
        // The protocol job reads the transcript from the DB. If the meeting
        // already has one, enqueue the job straight away; otherwise transcribe
        // first (the SYNC route persists), then enqueue.
        if (scr.hasTranscript)
            startProtocolJob()
        else {
            st = "transcribing"
            transcribeReq.post("/api/v1/transcribe",
                               { "path": audioPath, "meeting_id": meetingId })
        }
    }

    function startProtocolJob() {
        st = "generating"
        var body = { "kind": "protocol" }
        if (templateName.trim().length > 0)
            body["template_name"] = templateName.trim()
        protocolJobReq.post("/api/v1/meetings/" + meetingId + "/reprocess", body)
    }

    Request {
        id: transcribeReq
        onOk: function (j) {
            scr.store.refresh() // has_transcript flips
            scr.startProtocolJob()
        }
        onFail: function (s, e) {
            scr.errorMsg = e
            scr.st = "transcriptFailed"
        }
    }

    Request {
        id: protocolJobReq
        // 202 with the enqueued job id → the PipelineProgress below picks up
        // `scr.jobId`, polls the job, and navigates to the detail on completion.
        onOk: function (j) { scr.jobId = j.job_id }
        onFail: function (s, e) {
            scr.errorMsg = e
            scr.st = "failed"
        }
    }

    function onProtocolJobFinished(status, job) {
        if (status === "done") {
            scr.st = "done"
            scr.store.refresh()
            scr.shell.showDetail({
                "id": scr.meetingId, "name": scr.meetingName,
                "audio_path": scr.audioPath, "has_transcript": true,
                "created_at": 0
            })
        } else {
            scr.errorMsg = (job && job.last_error)
                    ? job.last_error
                    : qsTr("Не удалось сгенерировать протокол")
            scr.st = "failed"
        }
    }

    Component.onCompleted: {
        if (SettingsStore.loaded) templateName = SettingsStore.defaultTemplate()
        else SettingsStore.refresh()
        if (autoStart && st === "idle") generate()
    }

    background: Rectangle { color: Theme.paper }

    ColumnLayout {
        anchors.fill: parent
        spacing: 0

        RowLayout {
            Layout.fillWidth: true
            Layout.preferredHeight: 64
            Layout.maximumHeight: 64
            Layout.leftMargin: 24
            Layout.rightMargin: 24
            Layout.topMargin: 16
            Layout.bottomMargin: 16
            spacing: 12

            MeetyButton {
                variant: "ghost"
                iconName: "arrow-left"
                text: qsTr("Назад")
                enabled: scr.st === "idle" || scr.st === "transcriptFailed"
                         || scr.st === "failed"
                onClicked: scr.shell.showList()
            }
            Text {
                Layout.fillWidth: true
                text: qsTr("Генерация протокола")
                font.family: Theme.fontSerif
                font.pixelSize: Theme.fsTitle
                font.weight: Theme.wMedium
                font.letterSpacing: Theme.tracking(Theme.fsTitle, -0.02)
                color: Theme.ink
                elide: Text.ElideRight
            }
            Rectangle {
                radius: 999
                implicitWidth: pillRow.implicitWidth + 20
                implicitHeight: 26
                color: scr.st === "failed" || scr.st === "transcriptFailed"
                       ? Theme.paper3 : Theme.accentTint
                Row {
                    id: pillRow
                    anchors.centerIn: parent
                    spacing: 7
                    Rectangle {
                        anchors.verticalCenter: parent.verticalCenter
                        width: 6; height: 6; radius: 3
                        color: scr.st === "failed" || scr.st === "transcriptFailed"
                               ? Theme.rec : Theme.accent
                        SequentialAnimation on opacity {
                            running: scr.st === "transcribing" || scr.st === "generating"
                            loops: Animation.Infinite
                            NumberAnimation { from: 1.0; to: 0.35; duration: 700 }
                            NumberAnimation { from: 0.35; to: 1.0; duration: 700 }
                        }
                    }
                    Text {
                        anchors.verticalCenter: parent.verticalCenter
                        text: scr.stateLabel()
                        font.family: Theme.fontUi
                        font.pixelSize: Theme.fsSmall
                        font.weight: Theme.wSemiBold
                        color: scr.st === "failed" || scr.st === "transcriptFailed"
                               ? Theme.rec : Theme.accent2
                    }
                }
            }
        }

        Rectangle { Layout.fillWidth: true; height: 1; color: Theme.rule }

        // ── idle ────────────────────────────────────────────────────────────
        ScrollView {
            visible: scr.st === "idle"
            Layout.fillWidth: true
            Layout.fillHeight: true
            clip: true
            contentWidth: availableWidth
            ScrollBar.horizontal.policy: ScrollBar.AlwaysOff

            ColumnLayout {
                width: Math.min(720, parent.width - 48)
                anchors.horizontalCenter: parent.horizontalCenter
                spacing: 22

                Item { Layout.preferredHeight: 24 }
                Rectangle {
                    Layout.fillWidth: true
                    implicitHeight: idleCard.implicitHeight + 40
                    radius: Theme.rLg
                    color: Theme.paperSub
                    border.width: 1
                    border.color: Theme.rule

                    ColumnLayout {
                        id: idleCard
                        anchors.left: parent.left
                        anchors.right: parent.right
                        anchors.verticalCenter: parent.verticalCenter
                        anchors.margins: 28
                        spacing: 0

                        Text {
                            Layout.fillWidth: true
                            text: scr.templateName.length > 0
                                  ? scr.templateName : qsTr("Простой протокол")
                            horizontalAlignment: Text.AlignHCenter
                            font.family: Theme.fontUi
                            font.pixelSize: Theme.fsMicro
                            font.weight: Theme.wSemiBold
                            font.letterSpacing: Theme.tracking(Theme.fsMicro, 0.16)
                            color: Theme.ink3
                        }
                        Text {
                            Layout.fillWidth: true
                            Layout.topMargin: 6
                            text: scr.meetingName
                            horizontalAlignment: Text.AlignHCenter
                            wrapMode: Text.WordWrap
                            font.family: Theme.fontSerif
                            font.pixelSize: Theme.fsTitle
                            font.weight: Theme.wMedium
                            font.letterSpacing: Theme.tracking(Theme.fsTitle, -0.02)
                            color: Theme.ink
                        }
                        Text {
                            Layout.fillWidth: true
                            Layout.topMargin: 4
                            Layout.bottomMargin: 18
                            text: scr.hasTranscript
                                  ? qsTr("Транскрипт готов")
                                  : qsTr("Транскрипция будет запущена автоматически")
                            horizontalAlignment: Text.AlignHCenter
                            font.family: Theme.fontUi
                            font.pixelSize: Theme.fsSmall
                            color: Theme.ink3
                        }

                        RowLayout {
                            Layout.fillWidth: true
                            Layout.bottomMargin: 18
                            spacing: 0
                            Repeater {
                                model: [qsTr("Подготовка"), qsTr("Транскрипция"), qsTr("Протокол")]
                                delegate: ColumnLayout {
                                    required property var modelData
                                    required property int index
                                    Layout.fillWidth: true
                                    spacing: 9
                                    Rectangle {
                                        Layout.alignment: Qt.AlignHCenter
                                        width: 36; height: 36; radius: 18
                                        color: index === 0 ? Theme.paper : Theme.paper
                                        border.width: 1
                                        border.color: index === 0 ? Theme.accent : Theme.rule2
                                        Rectangle {
                                            anchors.centerIn: parent
                                            visible: index === 0
                                            width: 44; height: 44; radius: 22
                                            color: Qt.rgba(Theme.accentTint.r, Theme.accentTint.g, Theme.accentTint.b, 0.75)
                                            z: -1
                                        }
                                        Text {
                                            anchors.centerIn: parent
                                            text: index + 1
                                            font.family: Theme.fontUi
                                            font.pixelSize: Theme.fsBody
                                            font.weight: Theme.wSemiBold
                                            color: index === 0 ? Theme.accent : Theme.ink3
                                        }
                                    }
                                    Text {
                                        Layout.fillWidth: true
                                        text: modelData
                                        horizontalAlignment: Text.AlignHCenter
                                        font.family: Theme.fontUi
                                        font.pixelSize: Theme.fsSmall
                                        font.weight: index === 0 ? Theme.wSemiBold : Theme.wMedium
                                        color: index === 0 ? Theme.ink : Theme.ink3
                                    }
                                }
                            }
                        }

                        Text {
                            Layout.fillWidth: true
                            Layout.bottomMargin: 8
                            text: qsTr("Шаблон протокола")
                            font.family: Theme.fontUi
                            font.pixelSize: Theme.fsSmall
                            font.weight: Theme.wSemiBold
                            color: Theme.ink3
                        }
                        MeetyField {
                            Layout.fillWidth: true
                            text: scr.templateName
                            placeholderText: qsTr("По умолчанию")
                            onEditingFinished: scr.templateName = text
                        }

                        MeetyButton {
                            Layout.fillWidth: true
                            Layout.topMargin: 18
                            variant: "accent"
                            large: true
                            iconName: "sparkle"
                            text: qsTr("Сгенерировать протокол")
                            onClicked: scr.generate()
                        }
                    }
                }
                Item { Layout.preferredHeight: 48 }
            }
        }

        // ── transcription phase (SYNC route, no job to poll) ─────────────────
        ColumnLayout {
            visible: scr.st === "transcribing"
            Layout.alignment: Qt.AlignCenter
            Layout.fillWidth: true
            Layout.fillHeight: true
            Layout.preferredWidth: Math.min(720, parent.width - 48)
            Layout.maximumWidth: 720
            spacing: 22

            Item { Layout.fillHeight: true }
            Rectangle {
                Layout.fillWidth: true
                implicitHeight: transcribingCard.implicitHeight + 40
                radius: Theme.rLg
                color: Theme.paperSub
                border.width: 1
                border.color: Theme.rule

                ColumnLayout {
                    id: transcribingCard
                    anchors.left: parent.left
                    anchors.right: parent.right
                    anchors.verticalCenter: parent.verticalCenter
                    anchors.margins: 28
                    spacing: 16

                    Text {
                        Layout.fillWidth: true
                        text: scr.meetingName
                        horizontalAlignment: Text.AlignHCenter
                        wrapMode: Text.WordWrap
                        font.family: Theme.fontSerif
                        font.pixelSize: Theme.fsTitle
                        font.weight: Theme.wMedium
                        color: Theme.ink
                    }
                    Text {
                        Layout.fillWidth: true
                        text: qsTr("Транскрипция аудио…")
                        horizontalAlignment: Text.AlignHCenter
                        font.family: Theme.fontUi
                        font.pixelSize: Theme.fsBodyLg
                        font.weight: Theme.wMedium
                        color: Theme.ink2
                    }
                    Rectangle {
                        id: transcribeTrack
                        Layout.fillWidth: true
                        implicitHeight: 4
                        radius: 2
                        color: Theme.paper3
                        clip: true
                        Rectangle {
                            id: transcribeFill
                            width: Math.max(80, transcribeTrack.width * 0.35)
                            height: parent.height
                            radius: 2
                            color: Theme.accent
                            SequentialAnimation on x {
                                running: scr.st === "transcribing"
                                loops: Animation.Infinite
                                NumberAnimation {
                                    from: -transcribeFill.width
                                    to: transcribeTrack.width + transcribeFill.width
                                    duration: 1400
                                    easing.type: Easing.InOutCubic
                                }
                            }
                        }
                    }
                    Text {
                        Layout.fillWidth: true
                        text: qsTr("Это может занять несколько минут")
                        horizontalAlignment: Text.AlignHCenter
                        font.family: Theme.fontMono
                        font.pixelSize: Theme.fsSmall
                        color: Theme.ink3
                    }
                }
            }
            Item { Layout.fillHeight: true }
        }

        // ── protocol-job phase (polled via the shared PipelineProgress) ──────
        ColumnLayout {
            visible: scr.st === "generating" || scr.st === "done"
            Layout.alignment: Qt.AlignCenter
            Layout.fillWidth: true
            Layout.fillHeight: true
            Layout.preferredWidth: Math.min(720, parent.width - 48)
            Layout.maximumWidth: 720
            spacing: 22

            Item { Layout.fillHeight: true }
            Rectangle {
                Layout.fillWidth: true
                implicitHeight: progressCard.implicitHeight + 40
                radius: Theme.rLg
                color: Theme.paperSub
                border.width: 1
                border.color: Theme.rule

                ColumnLayout {
                    id: progressCard
                    anchors.left: parent.left
                    anchors.right: parent.right
                    anchors.verticalCenter: parent.verticalCenter
                    anchors.margins: 28
                    spacing: 16

                    Text {
                        Layout.fillWidth: true
                        text: scr.templateName.length > 0
                              ? scr.templateName : qsTr("Простой протокол")
                        horizontalAlignment: Text.AlignHCenter
                        font.family: Theme.fontUi
                        font.pixelSize: Theme.fsMicro
                        font.weight: Theme.wSemiBold
                        font.letterSpacing: Theme.tracking(Theme.fsMicro, 0.16)
                        color: Theme.ink3
                    }
                    Text {
                        Layout.fillWidth: true
                        text: scr.meetingName
                        horizontalAlignment: Text.AlignHCenter
                        wrapMode: Text.WordWrap
                        font.family: Theme.fontSerif
                        font.pixelSize: Theme.fsTitle
                        font.weight: Theme.wMedium
                        font.letterSpacing: Theme.tracking(Theme.fsTitle, -0.02)
                        color: Theme.ink
                    }

                    PipelineProgress {
                        Layout.fillWidth: true
                        apiClient: api
                        // Empty until the job is enqueued; start() is a no-op for "".
                        jobId: scr.st === "generating" ? scr.jobId : ""
                        onOpenSettings: scr.shell.showSettings()
                        onFinished: function (status, job) {
                            scr.onProtocolJobFinished(status, job)
                        }
                    }
                }
            }
            Item { Layout.fillHeight: true }
        }

        // ── error (transcriptFailed / failed) ───────────────────────────────
        ColumnLayout {
            visible: scr.st === "transcriptFailed" || scr.st === "failed"
            Layout.alignment: Qt.AlignCenter
            Layout.fillWidth: true
            Layout.fillHeight: true
            Layout.preferredWidth: Math.min(560, parent.width - 64)
            Layout.maximumWidth: 560
            spacing: 16
            Item { Layout.fillHeight: true }
            Text {
                Layout.fillWidth: true
                horizontalAlignment: Text.AlignHCenter
                wrapMode: Text.WordWrap
                font.family: Theme.fontUi
                font.pixelSize: Theme.fsBodyLg
                color: Theme.rec
                text: qsTr("Ошибка: %1").arg(scr.errorMsg)
            }
            MeetyButton {
                Layout.alignment: Qt.AlignHCenter
                text: qsTr("Повторить")
                onClicked: scr.generate()
            }
            Item { Layout.fillHeight: true }
        }
    }
}
