#!/usr/bin/env bash
# Render a release-pinned Homebrew Cask for the ad-hoc signed / un-notarized
# macOS DMG. This script is the SINGLE SOURCE OF TRUTH for the cask — there is
# no static .rb checked in, so the two can't drift.
#
# Why everything is pinned literally (url + sha256 + version) rather than
# interpolated from `version`: a prerelease tag (v0.1.0-alpha.7) differs from
# the DMG-embedded version (0.1.0), so a `url ".../#{version}/MeetingAssistant-#{version}.dmg"`
# cask would point at a file that doesn't exist. We pin the real tag + real DMG
# name + real checksum instead.
#
# The emitted cask's `version` is the tag without the leading `v`
# (e.g. 0.1.0-alpha.7) — unique per release so `brew upgrade` detects new alpha
# builds even while the app's marketing version stays 0.1.0.
#
# Usage: render-release-cask.sh <tag> <dmg> <out.rb> [owner/repo]
set -euo pipefail

if [[ $# -lt 3 || $# -gt 4 ]]; then
    echo "Usage: render-release-cask.sh <tag> <dmg> <out.rb> [owner/repo]" >&2
    exit 2
fi

TAG="$1"
DMG="$2"
OUT="$3"
REPO="${4:-medvedevD/meeting-assistant}"

[[ "$TAG" == v* ]] || { echo "Error: tag must start with v: $TAG" >&2; exit 1; }
[[ -f "$DMG" ]] || { echo "Error: DMG not found: $DMG" >&2; exit 1; }
[[ "$REPO" == */* ]] || { echo "Error: repo must look like owner/name: $REPO" >&2; exit 1; }

DMG_NAME="$(basename "$DMG")"
SHA_LINE="$(shasum -a 256 "$DMG")"
SHA="${SHA_LINE%% *}"
URL="https://github.com/$REPO/releases/download/$TAG/$DMG_NAME"
VERSION="${TAG#v}"
OWNER="${REPO%%/*}"
# Homebrew lowercases tap user names; use the lowercase form in the install hint
# so it matches what `brew` prints.
OWNER_LC="$(printf '%s' "$OWNER" | tr '[:upper:]' '[:lower:]')"

mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<CASK
# Homebrew Cask for Meeting Assistant (macOS).
# GENERATED by packaging/macos/render-release-cask.sh — do not edit by hand.
#
# Free (un-notarized) channel: the app is ad-hoc signed and NOT notarized (no
# paid Apple Developer ID — see packaging/macos/HOMEBREW-SUNSET.md). The
# postflight strips com.apple.quarantine so Gatekeeper does not wall off the app
# on a clean machine. Lives in a SELF-HOSTED tap (homebrew/cask will not accept
# an un-notarized cask). Install (Homebrew 6+ asks you to \`brew trust\` it once,
# because the postflight runs a command to strip the quarantine flag):
#
#   brew tap $OWNER_LC/meeting-assistant
#   brew install --cask meeting-assistant
cask "meeting-assistant" do
  version "$VERSION"
  sha256 "$SHA"

  url "$URL",
      verified: "github.com/$REPO/"
  name "Meeting Assistant"
  desc "Record, transcribe, and generate meeting protocols"
  homepage "https://github.com/$REPO"

  auto_updates false
  depends_on macos: :ventura # macOS 13 floor (ScreenCaptureKit)

  app "MeetingAssistant.app"

  # Un-notarized: drop the quarantine xattr so the app launches on a clean Mac
  # without the Gatekeeper "cannot verify" wall. This is the entire reason the
  # cask exists for the free channel (see packaging/macos/HOMEBREW-SUNSET.md).
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/MeetingAssistant.app"]
  end

  uninstall quit: "com.meeting-assistant.app"

  # Clean uninstall: mirror the Rust core's XDG-style layout on macOS
  # (rust/crates/app/src/container.rs + adapters/src/settings_store.rs).
  zap trash: [
    "~/.cache/meeting-assistant",
    "~/.config/meeting-assistant",
    "~/.local/share/meeting-assistant",
  ]
end
CASK

echo "Rendered cask: $OUT"
echo "  tag:     $TAG"
echo "  version: $VERSION"
echo "  dmg:     $DMG_NAME"
echo "  sha256:  $SHA"
