# Single-source-of-truth codegen for the IPC protocol version.
#
# The Rust server defines `PROTOCOL_VERSION` exactly once
# (rust/crates/api/src/lib.rs). The Qt client must NOT hand-maintain a second
# copy — it would silently drift. This script parses the Rust constant and
# emits `ClientProtocol.h` with `kClientProtocol`. Run via `cmake -P` from a
# custom command that DEPENDS on the Rust file, so the header is regenerated
# whenever the source of truth changes.
#
# Inputs (via -D): RUST_LIB (path to api/src/lib.rs), OUT (header path).

if(NOT DEFINED RUST_LIB OR NOT DEFINED OUT)
    message(FATAL_ERROR "GenClientProtocol.cmake: RUST_LIB and OUT are required")
endif()

if(NOT EXISTS "${RUST_LIB}")
    message(FATAL_ERROR "GenClientProtocol.cmake: Rust source not found: ${RUST_LIB}")
endif()

file(READ "${RUST_LIB}" _src)

# Match `const PROTOCOL_VERSION: u32 = <N>`. Anchoring on `const ` (not `pub`)
# makes this robust at start-of-file; it never matches `const
# MIN_PROTOCOL_VERSION` since that substring is `MIN_PROTOCOL_VERSION`.
if(NOT _src MATCHES "const +PROTOCOL_VERSION: *u32 *= *([0-9]+)")
    message(FATAL_ERROR
        "GenClientProtocol.cmake: could not find `pub const PROTOCOL_VERSION: u32 = N;` "
        "in ${RUST_LIB} — the IPC version gate cannot be generated.")
endif()
set(_proto "${CMAKE_MATCH_1}")

set(_content
"// @generated by qt-app/cmake/GenClientProtocol.cmake — DO NOT EDIT.
//
// Mirror of the Rust single source of truth:
//   ${RUST_LIB}
//   pub const PROTOCOL_VERSION: u32 = ${_proto};
//
// This is the IPC protocol version the Qt GUI speaks. The version gate (Q9)
// proceeds iff kClientProtocol is within the server's [min_protocol, protocol].
#pragma once
#include <QtGlobal>

namespace meetingassistant {
constexpr quint32 kClientProtocol = ${_proto};
}
")

# Write only when the content actually changes — avoids needless recompiles of
# every translation unit that includes this header.
set(_existing "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" _existing)
endif()
if(NOT _existing STREQUAL _content)
    file(WRITE "${OUT}" "${_content}")
    message(STATUS "GenClientProtocol: kClientProtocol = ${_proto} -> ${OUT}")
endif()
