from enum import Enum


class MeetingStatus(str, Enum):
    CREATED = "CREATED"
    AUDIO_READY = "AUDIO_READY"
    TRANSCRIBING = "TRANSCRIBING"
    TRANSCRIBED = "TRANSCRIBED"
    GENERATING = "GENERATING"
    COMPLETED = "COMPLETED"
    ARCHIVED = "ARCHIVED"
    TRANSCRIBE_FAILED = "TRANSCRIBE_FAILED"
    PROTOCOL_FAILED = "PROTOCOL_FAILED"
    CANCELLED = "CANCELLED"
